ALTER TABLE IF EXISTS public.accountaddress
  ALTER COLUMN "isDefault" TYPE boolean
  USING ("isDefault" = B'1');

DO $$
DECLARE
  current_max bigint;
BEGIN
  IF to_regclass('public.accountaddress') IS NOT NULL THEN
    CREATE SEQUENCE IF NOT EXISTS public.accountaddress_account_address_id_seq;
    SELECT COALESCE(MAX(account_address_id), 0) INTO current_max FROM public.accountaddress;
    PERFORM setval('public.accountaddress_account_address_id_seq', GREATEST(current_max, 1), current_max > 0);
    ALTER TABLE public.accountaddress ALTER COLUMN account_address_id SET DEFAULT nextval('public.accountaddress_account_address_id_seq');
  END IF;

  IF to_regclass('public.contact') IS NOT NULL THEN
    CREATE SEQUENCE IF NOT EXISTS public.contact_contact_id_seq;
    SELECT COALESCE(MAX(contact_id), 0) INTO current_max FROM public.contact;
    PERFORM setval('public.contact_contact_id_seq', GREATEST(current_max, 1), current_max > 0);
    ALTER TABLE public.contact ALTER COLUMN contact_id SET DEFAULT nextval('public.contact_contact_id_seq');
  END IF;

  IF to_regclass('public.discount') IS NOT NULL THEN
    CREATE SEQUENCE IF NOT EXISTS public.discount_disscount_id_seq;
    SELECT COALESCE(MAX(disscount_id), 0) INTO current_max FROM public.discount;
    PERFORM setval('public.discount_disscount_id_seq', GREATEST(current_max, 1), current_max > 0);
    ALTER TABLE public.discount ALTER COLUMN disscount_id SET DEFAULT nextval('public.discount_disscount_id_seq');
  END IF;

  IF to_regclass('public.feedback') IS NOT NULL THEN
    CREATE SEQUENCE IF NOT EXISTS public.feedback_feedback_id_seq;
    SELECT COALESCE(MAX(feedback_id), 0) INTO current_max FROM public.feedback;
    PERFORM setval('public.feedback_feedback_id_seq', GREATEST(current_max, 1), current_max > 0);
    ALTER TABLE public.feedback ALTER COLUMN feedback_id SET DEFAULT nextval('public.feedback_feedback_id_seq');
  END IF;

  IF to_regclass('public.orderaddress') IS NOT NULL THEN
    CREATE SEQUENCE IF NOT EXISTS public.orderaddress_orderAddressId_seq;
    SELECT COALESCE(MAX("orderAddressId"), 0) INTO current_max FROM public.orderaddress;
    PERFORM setval('public.orderaddress_orderAddressId_seq', GREATEST(current_max, 1), current_max > 0);
    ALTER TABLE public.orderaddress ALTER COLUMN "orderAddressId" SET DEFAULT nextval('public.orderaddress_orderAddressId_seq');
  END IF;

  IF to_regclass('public.payment') IS NOT NULL THEN
    CREATE SEQUENCE IF NOT EXISTS public.payment_payment_id_seq;
    SELECT COALESCE(MAX(payment_id), 0) INTO current_max FROM public.payment;
    PERFORM setval('public.payment_payment_id_seq', GREATEST(current_max, 1), current_max > 0);
    ALTER TABLE public.payment ALTER COLUMN payment_id SET DEFAULT nextval('public.payment_payment_id_seq');
  END IF;

  IF to_regclass('public.replyfeedback') IS NOT NULL THEN
    CREATE SEQUENCE IF NOT EXISTS public.replyfeedback_rep_feedback_id_seq;
    SELECT COALESCE(MAX(rep_feedback_id), 0) INTO current_max FROM public.replyfeedback;
    PERFORM setval('public.replyfeedback_rep_feedback_id_seq', GREATEST(current_max, 1), current_max > 0);
    ALTER TABLE public.replyfeedback ALTER COLUMN rep_feedback_id SET DEFAULT nextval('public.replyfeedback_rep_feedback_id_seq');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.wishlist (
  wishlist_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id integer NOT NULL,
  product_id integer NOT NULL,
  create_at timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT wishlist_account_product_unique UNIQUE (account_id, product_id)
);
